server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: product-service

logging:
  level:
    root: INFO
    com.example.meli.comparator: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html